"""添加 CourseSelection 与 Course 的关系

Revision ID: 008824b9b563
Revises: 967a9c6f9400
Create Date: 2026-04-08 13:21:07.901165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008824b9b563'
down_revision = '967a9c6f9400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.drop_column('attachment_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_path', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
