"""add system_settings table

Revision ID: 64cd0b534b35
Revises: 4061496df0a3
Create Date: 2026-04-09 21:25:10.469412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cd0b534b35'
down_revision = '4061496df0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('background_type', sa.String(length=20), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('background_gradient_start', sa.String(length=20), nullable=True),
    sa.Column('background_gradient_end', sa.String(length=20), nullable=True),
    sa.Column('background_image', sa.String(length=500), nullable=True),
    sa.Column('background_image_opacity', sa.Float(), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('saturation', sa.Integer(), nullable=True),
    sa.Column('brightness', sa.Integer(), nullable=True),
    sa.Column('hue_shift', sa.Integer(), nullable=True),
    sa.Column('border_radius', sa.String(length=20), nullable=True),
    sa.Column('card_style', sa.String(length=20), nullable=True),
    sa.Column('animation_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
