"""初始创建所有表

Revision ID: 967a9c6f9400
Revises: 
Create Date: 2026-04-07 22:55:16.884679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '967a9c6f9400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.drop_column('attachment_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_path', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
