"""add grade and major to users

Revision ID: bb68b699eab7
Revises: 64cd0b534b35
Create Date: 2026-04-10 15:39:26.384554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb68b699eab7'
down_revision = '64cd0b534b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('major')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
